package pl.kostrowski.mtga.model;

import javax.persistence.*;

/**
 * <h1>User </h1>
 * A simple class where user credentials and role will be stored.
 * {@code id} is an autogenerated integer <br>
 * {@code name and surname} will identify person <br>
 * {@code role} will specify what user can and can't do.

 * @author Krzysztof Ostrowski
 */


@Entity
@Table(name = "mtga_user")
public class User {

    @Id
    @Column(name = "id", unique = true)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "name")
    private String name;

    @Column(name = "surname")
    private String surname;

    @Column(name = "role")
    private String role;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
